"""Curated starter vocabulary.

``frecuencia_espanol.xlsx`` is a frequency-oriented teaching list, not an export
of a documented corpus. Ranks are a practical order, not corpus counts.
"""

from __future__ import annotations

MIS_PALABRAS: list[tuple[str, str]] = [
    ("mamá", "familia"),
    ("papá", "familia"),
    ("abuela", "familia"),
    ("abuelo", "familia"),
    ("bebé", "familia"),
    ("hermano", "familia"),
    ("hermana", "familia"),
    ("tío", "familia"),
    ("tía", "familia"),
    ("niño", "familia"),
    ("gato", "animales"),
    ("perro", "animales"),
    ("oso", "animales"),
    ("pez", "animales"),
    ("pato", "animales"),
    ("vaca", "animales"),
    ("rana", "animales"),
    ("lobo", "animales"),
    ("mono", "animales"),
    ("pájaro", "animales"),
    ("conejo", "animales"),
    ("caballo", "animales"),
    ("gallina", "animales"),
    ("tortuga", "animales"),
    ("león", "animales"),
    ("ratón", "animales"),
    ("oveja", "animales"),
    ("cerdo", "animales"),
    ("elefante", "animales"),
    ("pollito", "animales"),
    ("mano", "cuerpo"),
    ("pie", "cuerpo"),
    ("ojo", "cuerpo"),
    ("boca", "cuerpo"),
    ("nariz", "cuerpo"),
    ("oreja", "cuerpo"),
    ("cabeza", "cuerpo"),
    ("pelo", "cuerpo"),
    ("dedo", "cuerpo"),
    ("brazo", "cuerpo"),
    ("casa", "casa"),
    ("cama", "casa"),
    ("mesa", "casa"),
    ("silla", "casa"),
    ("puerta", "casa"),
    ("ventana", "casa"),
    ("cocina", "casa"),
    ("baño", "casa"),
    ("sofá", "casa"),
    ("cuna", "casa"),
    ("agua", "comida"),
    ("pan", "comida"),
    ("leche", "comida"),
    ("sopa", "comida"),
    ("arroz", "comida"),
    ("huevo", "comida"),
    ("manzana", "comida"),
    ("plátano", "comida"),
    ("queso", "comida"),
    ("galleta", "comida"),
    ("pelota", "juguetes"),
    ("muñeca", "juguetes"),
    ("coche", "juguetes"),
    ("tren", "juguetes"),
    ("globo", "juguetes"),
    ("osito", "juguetes"),
    ("cubo", "juguetes"),
    ("libro", "juguetes"),
    ("tambor", "juguetes"),
    ("puzzle", "juguetes"),
    ("sol", "naturaleza"),
    ("luna", "naturaleza"),
    ("estrella", "naturaleza"),
    ("árbol", "naturaleza"),
    ("flor", "naturaleza"),
    ("nube", "naturaleza"),
    ("lluvia", "naturaleza"),
    ("mar", "naturaleza"),
    ("río", "naturaleza"),
    ("hoja", "naturaleza"),
    ("rojo", "colores"),
    ("azul", "colores"),
    ("verde", "colores"),
    ("amarillo", "colores"),
    ("blanco", "colores"),
    ("negro", "colores"),
    ("rosa", "colores"),
    ("naranja", "colores"),
    ("morado", "colores"),
    ("gris", "colores"),
    ("come", "acciones"),
    ("bebe", "acciones"),
    ("duerme", "acciones"),
    ("juega", "acciones"),
    ("corre", "acciones"),
    ("salta", "acciones"),
    ("mira", "acciones"),
    ("ríe", "acciones"),
    ("lava", "acciones"),
    ("abraza", "acciones"),
    ("hola", "otros"),
    ("adiós", "otros"),
    ("gracias", "otros"),
    ("grande", "otros"),
    ("pequeño", "otros"),
]

# Approximate frequency order for the secondary reservoir. Function words come
# first because they are frequent; the scheduler postpones them when building sets.
FUNCTION_WORDS: list[str] = [
    "de", "la", "que", "el", "en", "y", "a", "los", "del", "se",
    "las", "un", "por", "con", "no", "una", "su", "para", "es", "al",
    "lo", "como", "más", "pero", "sus", "le", "ya", "o", "fue", "ha",
    "sí", "porque", "esta", "entre", "cuando", "muy", "sin", "sobre", "también", "me",
    "hasta", "hay", "donde", "desde", "todo", "nos", "durante", "todos", "uno", "les",
    "ni", "contra", "otros", "ese", "eso", "ante", "ellos", "esto", "mí", "antes",
    "algunos", "qué", "unos", "yo", "otro", "otras", "otra", "él", "tanto", "esa",
    "estos", "mucho", "quienes", "nada", "muchos", "cual", "poco", "ella", "estar", "estas",
    "algunas", "algo", "nosotros", "mi", "mis", "tú", "te", "ti", "tu", "tus",
    "ser", "haber", "son", "era", "han", "he", "has", "hemos", "soy", "eres",
    "somos", "está", "están", "estoy", "estamos", "estás", "eran", "sido", "si", "bien",
    "mal", "aquí", "allí", "ahí", "ahora", "entonces", "después", "luego", "así", "solo",
    "cada", "toda", "todas", "mismo", "misma", "mismos", "mismas", "cualquier", "alguien", "nadie",
    "nunca", "siempre", "tampoco", "quizá", "tal", "vez", "aún", "todavía", "casi", "menos",
    "bastante", "demasiado", "mejor", "peor", "mayor", "menor", "nuestro", "nuestra", "nuestros", "nuestras",
    "vuestro", "vuestra", "vuestros", "vuestras", "suyo", "suya", "suyos", "suyas", "os", "quien",
]

CONTENT_WORDS: list[str] = [
    "tiempo", "vida", "día", "hombre", "mujer", "niña", "persona", "gente", "año", "parte",
    "trabajo", "mundo", "país", "lugar", "hora", "momento", "forma", "caso", "grupo", "problema",
    "punto", "gobierno", "empresa", "número", "sistema", "programa", "historia", "ciudad", "padre", "madre",
    "hijo", "hija", "amigo", "amiga", "escuela", "clase", "maestro", "maestra", "noche", "mañana",
    "tarde", "tierra", "cielo", "montaña", "animal", "calle", "ropa", "zapato", "camisa", "color",
    "nuevo", "viejo", "bueno", "malo", "feliz", "triste", "bonito", "alto", "bajo", "largo",
    "corto", "rápido", "lento", "caliente", "frío", "lleno", "vacío", "abierto", "cerrado", "primero",
    "segundo", "tercero", "último", "cerca", "lejos", "dentro", "fuera", "arriba", "abajo", "delante",
    "detrás", "hoy", "ayer", "pronto", "amor", "miedo", "alegría", "dolor", "fuerza", "luz",
    "sombra", "fuego", "aire", "viento", "nieve", "piedra", "arena", "bosque", "jardín", "parque",
    "playa", "campo", "pueblo", "barrio", "camino", "puente", "plaza", "tienda", "mercado", "dinero",
    "precio", "fruta", "verdura", "carne", "pescado", "azúcar", "sal", "café", "té", "zumo",
    "vaso", "plato", "cuchara", "tenedor", "cuchillo", "botella", "caja", "bolsa", "papel", "lápiz",
    "cuaderno", "reloj", "teléfono", "música", "canción", "película", "foto", "dibujo", "pintura", "juguete",
    "regalo", "fiesta", "cumpleaños", "nombre", "palabra", "letra", "frase", "pregunta", "respuesta", "idea",
    "sueño", "cara", "diente", "corazón", "sangre", "médico", "hospital", "salud", "semana", "mes",
    "invierno", "verano", "otoño", "primavera", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado",
    "domingo", "enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre",
    "octubre", "noviembre", "diciembre", "cuento", "hada", "dragón", "nido", "pluma", "ala", "cola",
    "granja", "semilla", "planta", "raíz", "tronco", "rama", "pera", "uva", "fresa", "limón",
    "tomate", "patata", "zanahoria", "lechuga", "cebolla", "ajo", "aceite", "mantequilla", "helado", "chocolate",
    "yogur", "tostada", "bocadillo", "ensalada", "pollo", "jamón", "pizza", "pasta", "nevera", "horno",
    "sartén", "olla", "taza", "jarra", "grifo", "jabón", "toalla", "ducha", "bañera", "cepillo",
    "peine", "espejo", "escoba", "llave", "escalera", "pasillo", "salón", "techo", "suelo", "pared",
    "lámpara", "alfombra", "cojín", "cortina", "estantería", "armario", "cajón", "almohada", "sábana", "manta",
    "pañal", "biberón", "carrito", "columpio", "tobogán", "bicicleta", "patinete", "cometa", "circo", "payaso",
    "baile", "guitarra", "piano", "flauta", "radio", "televisión", "pantalla", "dado", "carta", "bloque",
    "pintar", "cuento", "página", "título", "imaginar", "soñar", "despertar", "caminar", "nadar", "volar",
    "viajar", "visitar", "compartir", "guardar", "esconder", "mostrar", "saludar", "agradecer", "coger", "soltar",
    "empujar", "abrir", "cerrar", "encender", "apagar", "romper", "arreglar", "limpiar", "ordenar", "barrer",
    "cocinar", "cortar", "mezclar", "oler", "escuchar", "ver", "pensar", "recordar", "olvidar", "aprender",
    "enseñar", "explicar", "preguntar", "responder", "contar", "cantar", "llorar", "gritar", "callar", "descansar",
    "estudiar", "leer", "escribir", "dibujar", "ganar", "perder", "ayudar", "cuidar", "querer", "besar",
    "acariciar", "sonreír", "esperar", "llegar", "salir", "entrar", "subir", "bajar", "volver", "seguir",
    "parar", "empezar", "terminar", "repetir", "intentar", "necesitar", "gustar", "crecer", "nacer", "vivir",
    "caer", "girar", "mojar", "secar", "lavar", "vestido", "falda", "chaqueta", "abrigo", "bufanda",
    "gorro", "guante", "pijama", "zapatilla", "sombrero", "gafas", "paraguas", "mochila", "timbre", "ascensor",
    "dormitorio", "cuadro", "perchero", "colchón", "chupete", "sonajero", "pala", "castillo", "patín", "pompa",
    "mago", "teatro", "teclado", "partida", "turno", "plastilina", "pincel", "crayón", "tijeras", "pegamento",
    "cartulina", "portada", "autor", "recortar", "pegar", "construir", "acostar", "levantar", "vestir", "peinar",
    "sentar", "trepar", "conducir", "invitar", "prestar", "devolver", "buscar", "encontrar", "señalar", "despedir",
    "pedir", "dar", "tirar", "arrastrar", "probar", "tocar", "observar", "susurrar", "trabajar", "jugar",
    "empatar", "abrazar", "enfadar", "calmar", "consolar", "poner", "quitar", "llevar", "traer", "dejar",
    "continuar", "practicar", "conseguir", "poder", "deber", "preferir", "elegir", "decidir", "cambiar", "enfermar",
    "curar", "doler", "chocar", "quemar", "ensuciar", "manchar", "planchar", "coser", "atar", "abrochar",
    "calzar", "pantalón", "calcetín", "bolsillo", "botón", "sandalia", "bota", "cartera", "candado", "alfombra",
    "mantel", "servilleta", "detergente", "lavadora", "cremallera", "azúcar", "mermelada", "galleta", "tarta", "caramelos",
    "cereales", "fideos", "aceite", "salchicha", "fregona", "cubo", "papel", "lápiz", "cuento", "niño",
    "árbol", "ratón", "león", "mamá", "papá", "casa", "agua", "pan", "sol", "luna",
    "rojo", "azul", "gato", "perro", "oso", "pez", "pato", "vaca", "rana", "lobo",
    "mono", "cama", "mesa", "mano", "pie", "ojo", "boca", "flor", "nube", "lluvia",
]

FUNCTION_WORD_SET = frozenset(word.casefold() for word in FUNCTION_WORDS)


def dedupe(words: list[str]) -> list[str]:
    seen: set[str] = set()
    unique: list[str] = []
    for word in words:
        key = word.casefold()
        if key in seen:
            continue
        seen.add(key)
        unique.append(word)
    return unique


def frequency_words() -> list[str]:
    """Return about 500 words, frequent function words first, then content words."""
    return dedupe(FUNCTION_WORDS + CONTENT_WORDS)[:500]
